### ISSUE TITLE
No module named guest.decorators

### ISSUE THREAD

**Issue by exp0nge** [yoanisgil/django-simple-forum#1]
I think you forgot a dependency. A `requirements.txt` would help.

**Comment by yoanisgil** [comment]
Yes. That would help for sure. Would be nice to know the exact issue you're facing ;). Let me know if I could be of any help.

**Comment by xczheng** [comment]
When I access the server:
ImportError at /django_simple_forum
No module named guest.decorators
Request Method:	GET
Request URL:	http://127.0.0.1:8000/django_simple_forum
Django Version:	1.8.17
Exception Type:	ImportError
Exception Value:	
No module named guest.decorators

**Comment by fzs1** [comment]
Hey did someone find the solution to the previous error?

**Comment by yoanisgil** [comment]
Going to try this with Django 1.10, is that what people are using?

**Comment by fzs1** [comment]
Yes ,

Django 1.10 (the latest version available) :)

Fatima

On 30 Jan 2017, at 19:58, Yoanis Gil <notifications@github.com<mailto:notifications@github.com>> wrote:


Going to try this with Django 1.10, is that what people are using?

-
